fix: CLIN-697 Deploy in staging bucket
Ferlab-Ste-Justine/clin-variant-etl pull request #114
Opened 2022-01-14 13:47 UTC by jecos

2022-01-14 15:00 UTC, creativeyann17 requested changes

2022-01-14 15:00 UTC, creativeyann17 commented on .github/workflows/deploy_minio_staging.yml
> +          bucket: 'clin-qa-staging-datalake'
TBC

2022-01-14 15:00 UTC, creativeyann17 commented on .github/workflows/deploy_minio_staging.yml
> +          endpoint: ${{ secrets.MINIO_CLIN_QA_AWS_ENDPOINT }}
secrets are for QA, is it ok ?

2022-01-17 15:28 UTC, Magnitus- approved these changes
LGTM

2022-01-17 15:33 UTC, botekchristophe approved these changes

2022-01-17 15:33 UTC, merged