feat: CLIN-1949 Enrich SNV with exomiser
Ferlab-Ste-Justine/clin-variant-etl pull request #286
Opened 2023-05-16 21:57 UTC by laurabegin

2023-05-17 14:31 UTC, kstonge commented on src/main/scala/bio/ferlab/clin/etl/qc/variantlist/SameListBetweenSNVAndVariants.scala
>        .filter($"ad_alt" >= 3)
Est-ce que le filtre est nécessaire entre ces deux tables?

2023-05-17 14:44 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/qc/variantlist/SameListBetweenSNVAndVariants.scala
>        .filter($"ad_alt" >= 3)
Je ne suis pas familière avec ce filtre. @jecos ?

2023-05-17 15:02 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/conf/EtlConfiguration.scala
> +      DatasetConf("enriched_snv"                   , clin_datalake, "/enriched/snv"                      , DELTA  , OverWrite, partitionby = List("chromosome"), table = Some(TableConf("clin", "snv"))
@kstonge J'ai spécifié que les variants sont uniques par `aliquot_id`, mais je vois dans tes tests que tu vérifies par `service_request_id`. Est-ce que ça s'équivaut? Est-ce que je devrais changer la clé ici?

2023-05-17 15:08 UTC, kstonge commented on src/main/scala/bio/ferlab/clin/etl/conf/EtlConfiguration.scala
> +      DatasetConf("enriched_snv"                   , clin_datalake, "/enriched/snv"                      , DELTA  , OverWrite, partitionby = List("chromosome"), table = Some(TableConf("clin", "snv"))
Avant j'utilisais patient_id, mais ce n'était pas bon. C'était une recommandation de Jérémy d'utiliser le service_request_id. Probablement que aliquot_id peut être bon aussi, mais j'aurais tendance à préférer service_request_id. Voyons ce que le maître @jecos en pense!

2023-05-17 15:56 UTC, creativeyann17 requested changes
Regenerer EtlConfiguration

2023-05-17 19:31 UTC, creativeyann17 approved these changes

2023-05-18 16:57 UTC, jecos commented on src/main/scala/bio/ferlab/clin/etl/qc/variantlist/SameListBetweenSNVAndVariants.scala
>        .filter($"ad_alt" >= 3)
Normalement non, les ad_alt < 3 devrait tout le temps etre supprimés en amont

2023-05-18 16:59 UTC, jecos commented on src/main/scala/bio/ferlab/clin/etl/conf/EtlConfiguration.scala
> +      DatasetConf("enriched_snv"                   , clin_datalake, "/enriched/snv"                      , DELTA  , OverWrite, partitionby = List("chromosome"), table = Some(TableConf("clin", "snv"))
Ilsne devriaent pas y avoir de problème à utiliser l'un ou l'autre. J'aurais tendance à garder aliquot_id, si on veut implementer la meme chose dans les autres projets.

2023-05-19 17:36 UTC, jecos approved these changes

2023-05-19 17:49 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/qc/variantlist/SameListBetweenSNVAndVariants.scala
>        .filter($"ad_alt" >= 3)
J'ai retiré le filtre dans ce test

2023-05-19 18:11 UTC, merged