feat: clin-1946 use score column instead of rankscore
Ferlab-Ste-Justine/clin-variant-etl pull request #297
Opened 2023-06-07 17:49 UTC by ethienneroy

feat: clin-1946 renamed all rankscore to score

feat: clin-1946 added consequences phyloP100way_vertebrate attribute

2023-06-07 17:51 UTC, ethienneroy commented
recreated pull request because the other wasn't updating

2023-06-07 17:59 UTC, ethienneroy commented
WIP - addding corrections from last PR review

2023-06-09 15:42 UTC, creativeyann17 requested changes
When datalake-lib `6.4.0` will be available:
- change in `build.sbt datalakeSpark3Version`
- regenerate `EtlConfiguration`
- use the new fields `REVEL_score` and `LRT_score`

2023-06-09 18:15 UTC, jecos approved these changes

2023-06-14 20:30 UTC, creativeyann17 approved these changes

2023-06-14 20:42 UTC, merged