feat: CLIN-2026 SNV Somatic
Ferlab-Ste-Justine/clin-variant-etl pull request #304
Opened 2023-06-27 00:45 UTC by creativeyann17

**SNV Somatic**

Make VCF files optional
- [ ] add VCF optional feature in normalized SNV Germline
- [ ] add VCF optional feature in normalized Variants
- [ ] TUs

Add new ETL to normalized SNV Somatic
- [ ] update EtlConfiguration + build confs
- [ ] Add new normalized SNV Somatic
- [ ] TUs

Update further ETLs with Somatic join
- normalized Variants
- enriched Variants

2023-06-29 19:25 UTC, laurabegin requested changes

2023-06-29 19:25 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/normalized/package.scala
> +  def loadOptionalVCFDataFrame[T <: Product : ClassTag : TypeTag](location: String)(implicit spark: SparkSession): DataFrame = {
Le type de T est large je trouve. On pourrait créer un type pour les modèles de VCF SNV?

2023-06-29 19:25 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/normalized/SNVSomatic.scala
> +      //.withColumn("father_qd", fatherQD)
Code commenté

2023-06-29 19:25 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/normalized/SNVSomatic.scala
> +  override def defaultRepartition: DataFrame => DataFrame = RepartitionByColumns(Seq("chromosome"), Some(100))
Tu peux définir la répartition dans le DatasetConf de normalized_snv_somatic dans ETLConfiguration.

2023-07-03 22:05 UTC, creativeyann17 commented on src/main/scala/bio/ferlab/clin/etl/normalized/package.scala
> +  def loadOptionalVCFDataFrame[T <: Product : ClassTag : TypeTag](location: String)(implicit spark: SparkSession): DataFrame = {
Tres bonne idee

2023-07-03 22:06 UTC, creativeyann17 commented on src/main/scala/bio/ferlab/clin/etl/normalized/SNVSomatic.scala
> +      //.withColumn("father_qd", fatherQD)
je voulais les laisser pour voir avec Jeremy apres si c'est normal ou pas

2023-07-03 23:42 UTC, creativeyann17 commented on src/main/scala/bio/ferlab/clin/etl/normalized/package.scala
> +  def loadOptionalVCFDataFrame[T <: Product : ClassTag : TypeTag](location: String)(implicit spark: SparkSession): DataFrame = {
Par contre j'ai bcp de mal a creer un trait ou class qui implement c'est trois choses ...

2023-07-04 13:11 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/normalized/package.scala
> +  def loadOptionalVCFDataFrame[T <: Product : ClassTag : TypeTag](location: String)(implicit spark: SparkSession): DataFrame = {
Tu peux faire un trait VCF_SNV et extend ce trait dans tes case classes, non?

2023-07-04 14:34 UTC, jecos requested changes

2023-07-04 14:34 UTC, jecos commented on src/main/scala/bio/ferlab/clin/etl/normalized/SNVSomatic.scala
> +      //.withColumn("father_qd", fatherQD)
Pour le somatic, par definition, on ne devrait pas avoir d'inheritance. Je vais revoir la spec, mais ces champs ne devrait pas exister dans le cas du somatic.

2023-07-04 14:34 UTC, jecos commented on src/main/scala/bio/ferlab/clin/etl/normalized/package.scala
> +
A rediscuter

2023-07-13 14:54 UTC, laurabegin requested changes

2023-07-13 14:54 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/enriched/SNVSomaticTumorOnly.scala
> +    val exomiser = data(normalized_exomiser.id).selectLocus(
Code dupliqué. Ça pourrait être le même classe pour enriched.SNV, non? Juste à passer le dataset_id de snv.

2023-07-13 14:54 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/normalized/SNVSomaticTumorOnly.scala
> +class SNVSomaticTumorOnly(batchId: String)(implicit configuration: Configuration) extends Occurrences(batchId) {
Même chose ici. Presque tout est dupliqué avec normalized.SNV. Peut-être revoir le code pour éviter qu'on ait à maintenir deux classes quasi-identique?

2023-07-13 14:54 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/normalized/Variants.scala
> +  implicit var logger: Logger = log
Devrait être une val

2023-07-14 17:38 UTC, laurabegin approved these changes

2023-07-14 17:39 UTC, merged