Feat/clin 2570
Ferlab-Ste-Justine/clin-variant-etl pull request #358
Opened 2024-02-09 15:38 UTC by ethienneroy

2024-02-09 16:55 UTC, laurabegin requested changes

2024-02-09 16:55 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/normalized/SNVSomatic.scala
> +      data + (raw_variant_calling.id -> vcf(raw_variant_calling.location.replace("{{BATCH_ID}}", batchId), None, optional = true))
Ça fait déjà ça dans super.extract(). Pas besoin du if, faut juste caller super.extract() et rajouter rare_variants je crois

2024-02-09 20:18 UTC, laurabegin requested changes

2024-02-09 20:18 UTC, laurabegin commented on src/test/scala/bio/ferlab/clin/etl/normalized/SNVSomaticSpec.scala
> +  val raw_variant_calling: DatasetConf = conf.getDataset("raw_snv")//.copy(path = "{{BATCH_ID}}/11111.dragen.WES_somatic-tumor_only.hard-filtered.norm.VEP.vcf") // bat1
Retirer code commenté

2024-02-09 20:32 UTC, laurabegin approved these changes

2024-02-16 16:40 UTC, creativeyann17 requested changes

2024-02-16 16:40 UTC, creativeyann17 commented on src/main/scala/bio/ferlab/clin/etl/conf/EtlConfiguration.scala
> +      DatasetConf("raw_snv"                        , clin_import  , "/{{BATCH_ID}}/*.vcf.gz"           , VCF    , OverWrite),
`*.norm.VEP.vcf.gz` pour `raw_snv`

2024-02-16 17:04 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/conf/EtlConfiguration.scala
> +      DatasetConf("raw_snv"                        , clin_import  , "/{{BATCH_ID}}/*.vcf.gz"           , VCF    , OverWrite),
done

2024-02-16 17:10 UTC, creativeyann17 approved these changes

2024-02-16 18:53 UTC, merged