feat: CLIN-2531 Process snv somatic only+normal in enriched_snv_somatic
Ferlab-Ste-Justine/clin-variant-etl pull request #362
Opened 2024-03-07 21:25 UTC by laurabegin

2024-03-12 17:20 UTC, jecos requested changes

2024-03-26 20:34 UTC, laurabegin commented on src/main/resources/config/qa.conf
> +                "analysis_service_request_id"
Fait

2024-03-26 20:34 UTC, laurabegin commented on src/main/scala/bio/ferlab/clin/etl/enriched/SNVSomatic.scala
> +        val analysisServiceRequestIds: Seq[String] = normalizedSnvSomaticDf
Fait

2024-03-27 15:10 UTC, creativeyann17 commented on src/main/scala/bio/ferlab/clin/etl/enriched/SNVSomatic.scala
> +        val analysisServiceRequestIds: Seq[String] = enriched_clinical.read.where($"batch_id" === id)
:+1:

2024-03-27 15:21 UTC, creativeyann17 approved these changes

2024-03-27 15:22 UTC, merged